<?php 
  echo '<footer>';
  echo '<div id="footer1">';
  echo '<div id="leftcolumn">';
  echo '<div id="footerlogo">';
  echo '<img src="../images/cliniclogo.png" width="38" height="38" id="icon" />';
  echo '<h2>NTUClinic</h2>';
  echo '</div>';
  echo '<small>';
  echo '  <dt>55 Ubi Ave 1 #08-01 Singapore 408935';
  echo '  <br>Fax: 6590 4389';
  echo '  <br>Opens Monday to Friday, 8:30am to';
  echo '  <br><dt id="lowesttext">6:00pm, except Public Holidays ';
  echo '</small>';
  echo '</div>';
  echo '<div class="footernav">';
  echo '<h3 class="footerheader">Information</h3>';
  echo '<nav>';
  echo '  <ul>';
  echo '    <li><a href="about.php" id="botnav">About Us</a> </li>';
  echo '    <li><a href="doctor.php" id="botnav">Our Doctors</a> </li>';
  echo '    <li><a href="contact.php" id="botnav">Contact Us</a> </li>';
  echo '  </ul>';
  echo '</nav>';

  echo '</div>';
  echo '<div class="footernav">';
  echo '<h3 class="footerheader">Patient\'s Site</h3>';
  echo '<nav>';
  echo '<ul>';
  echo '    <li><a href="profile.php" id="botnav">Profile</a> </li>';
  echo '    <li><a href="myappointment.php" id="botnav">Your Appointments</a> </li>';
  echo '    <li><a href="bookappointment.php" id="botnav">Book Appointments</a> </li>';
  echo '  </ul>';
  echo '</nav>';
  echo '</div>';
  echo '<div id="rightcolumn">';
  echo '<p>Follow us through our social media.</p>';
  echo '<div id="socialmedia">';
  echo '<image src="images/facebook.png" width="35" height="35" id="contactlogo">';
  echo '<image src="images/instagram.png" width="35" height="35" id="contactlogo">';
  echo '<image src="images/whatsapp.png" width="35" height="35" id="contactlogo">';
  echo '</div>';
  echo '</div>';
  echo '</div>';
  echo '  <div id="copyright">';
  echo '<small><i>Copyright &copy; 2022 NTUClinic </small>';
      echo '</div>';
    echo '</footer>';

?>